---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects
      to: /home/vagrant/Projects

sites:
    - conf: demo.app
      servers:
        - map: static.demo.app
          to: /home/vagrant/Projects/Demo/static
          type: static

        - map: "demo.app *.demo.app"
          to: /home/vagrant/Projects/Demo

#databases:
#    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
