---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
box: jason-chang/centstead-usual
# 基础盒子版本 建议如果离线安装基础盒子再打开本设置
#version: ">=0"

# Provison 时是否重新部署 软件环境
provison_soft: true

# Provison 时如果存在同版软件是否重新安装
# provison_reinstall: true

# 导入本地公钥文件
# authorize: ~/.ssh/id_rsa.pub

# 导入本地私钥文件
# keys:
#    - ~/.ssh/id_rsa

# PHP 版本
# php: php70

# Mysql 版本
# mysql: mysql57

# PostgreSql 版本
# pgsql: pgsql95

# 共享文件夹
folders:
  - map: ~/ExampleDir
    to: /home/vagrant/ExampleDir

# 拷贝文件到虚拟机
#copy:
#  - from: ~/copy.example
#    to: /home/vagrant/copy.example


# 站点映射
sites:
  - conf: example.app
    servers:
      - map: static.example.app
        to: /home/vagrant/ExampleDir/example/static
        type: static

      - map: "example.app *.example.app"
        to: /home/vagrant/ExampleDir/example/public
        aliases: "example.app a.example.app u.example.app www.example.app"
        # schedule: true
        # port: 80
        # ssl: 443

# 计划任务
schedules:
  - name: redis_example
    user: vagrant
    interval: "* 0 */1 * *"
    command: "/usr/bin/redis-cli -h localhost DEL 'some-throttle'"

# Laravel 队列监听
#queues:
#  - name: example.app.mails
#    driver: redis
#    queue: emails
#    dir: /home/vagrant/Code/Demo

# 创建数据库
# databases:
#    - name: vagrant
#      db: mysql
#    - name: vagrant
#      db: pgsql

# 端口映射
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp